version: '3.7'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    init: true
    env_file:
      - .env
    environment:
      NODE_ENV: development # for now, until I have good prod logging
    volumes:
      - db-data:/home/node/app/prisma/db

volumes:
  db-data:
