version: '3.7'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    init: true
    env_file:
      - .env
    volumes:
      - db-data:/home/node/app/prisma/db

volumes:
  db-data:
