version: '3.7'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development # for now, until I have good prod logging
      USE_PINO_PRETTY: 'false'
    volumes:
      - ./:/home/node/app
