strictDepBuilds: true
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@sentry-internal/node-cpu-profiler': true
  '@sentry/cli': true
  '@sentry/profiling-node': true
  better-sqlite3: true
  esbuild: true
  prisma: true
  sharp: true

minimumReleaseAgeExclude:
  - sleetcord@4.3.1

minimumReleaseAgeStrict: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.9
  vite-plus: latest
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
