import type { APIEmbed, APIEmbedImage, Message } from 'discord.js'
import { notNullish } from 'sleetcord-common'

import { getRawMessage } from '../../../helpers/rawMessage.js'
import { normalizeUrl } from '../utils.js'

/** Discord doesn't seem to embed images over this size */
export const MAX_IMAGE_SIZE = 100 * 1024 * 1024

interface HashEntry {
  phash: string
  url: string
}

/**
 * Gets the phashes for all images (embeds and attachments) in a message, along with their URLs for reference. Uses the placeholder field, which is a Thumbhash generated by Discord
 *
 * @param message The message to hash embeds & attachments for
 * @returns A promise that resolves to an array of hashes (or filenames, if that's more efficient or if hashes aren't possible)
 */
export async function getImagePhashes(message: Message): Promise<HashEntry[]> {
  const rawMessage = getRawMessage(message)

  if (!rawMessage) {
    return []
  }

  const { attachments, embeds } = rawMessage

  const hashes = [
    embeds
      .map(getEmbedImage)
      .filter(notNullish)
      .map((e) => ({ phash: e.placeholder, url: normalizeUrl(e.url) })),
    attachments.map((a) => ({ phash: a.placeholder, url: normalizeUrl(a.url) })),
  ].flat()

  return hashes.filter((h): h is HashEntry => h.phash !== null)
}

function getEmbedImage(embed: APIEmbed): APIEmbedImage | null {
  return embed.image ?? embed.thumbnail ?? null
}
