import { writeFile } from 'node:fs/promises'

import { LimitedCollection, type EmbedAssetData, type Message } from 'discord.js'

import { getPhashImagePath } from '../commands/phash/utils.js'
import { normalizeUrl } from '../utils.js'
import { computeImagePhash } from './phash.js'

/** Discord doesn't seem to embed images over this size */
export const MAX_IMAGE_SIZE = 100 * 1024 * 1024

interface HashEntry {
  phash: string
  url: string
  contentType: string | null
  filePath: string | null
}

const IGNORED_CONTENT_TYPES = new Set(['image/gif', 'image/svg+xml'])

/**
 * Gets the phashes for all images (embeds and attachments) in a message, along with their URLs for reference. Uses the placeholder field, which is a Thumbhash generated by Discord
 *
 * @param message The message to hash embeds & attachments for
 * @returns A promise that resolves to an array of hashes (or filenames, if that's more efficient or if hashes aren't possible)
 */
export async function getImagePhashes(message: Message): Promise<HashEntry[]> {
  const imageUrls: string[] = [
    ...message.embeds
      .map((embed) => embed.image ?? embed.thumbnail)
      .filter((url): url is EmbedAssetData => Boolean(url))
      .map((image) => image.url),
    ...message.attachments
      .filter(
        (attachment) =>
          attachment.size <= MAX_IMAGE_SIZE &&
          attachment.contentType?.startsWith('image/') &&
          !IGNORED_CONTENT_TYPES.has(attachment.contentType),
      )
      .map((attachment) => attachment.url),
  ]

  const hashedEntries = await Promise.all(
    Array.from(imageUrls).map((url) => phashImage(url).catch(() => null)),
  )

  return hashedEntries.filter((entry): entry is HashEntry => entry !== null)
}

const phashCache = new LimitedCollection<string, HashEntry>({ maxSize: 100 })

/**
 * Fetch an image from a URL and compute its phash.
 *
 * Caches the latest 100 urls in memory
 *
 * @param url The URL of the image to fetch and hash
 * @param fileName An optional filename to associate with this image (used for attachments, where the URL may not be unique or consistent)
 * @returns A promise that resolves to a HashEntry containing the phash and related data, or null if the image couldn't be fetched or hashed
 */
export async function phashImage(url: string): Promise<HashEntry | null> {
  const normalizedUrl = normalizeUrl(url)
  const cached = phashCache.get(normalizedUrl)

  if (cached) {
    return cached
  }

  const image = await fetchImageBuffer(normalizedUrl).catch(() => null)

  if (!image) {
    return null
  }

  const imagePhash = await computeImagePhash(image.bytes).catch(() => null)

  if (!imagePhash) {
    return null
  }

  const filePath = getPhashImagePath(imagePhash, image.contentType)

  if (filePath) {
    await writeFile(filePath, image.bytes)
  }

  const entry: HashEntry = {
    phash: imagePhash,
    url: normalizedUrl,
    contentType: image.contentType,
    filePath,
  }

  phashCache.set(normalizedUrl, entry)

  return entry
}

/**
 * Fetches an image from a URL and returns its data as a buffer, along with the content type.
 *
 * @param url The URL to fetch the image from
 * @returns A promise that resolves to an object containing the image data and content type
 * @throws If the fetch fails, if the file isn't an image, or if the image is too large.
 */
export async function fetchImageBuffer(
  url: string,
): Promise<{ bytes: Uint8Array<ArrayBuffer>; contentType: string }> {
  const response = await fetch(url)

  if (!response.ok) {
    throw new Error(`Failed to fetch image from URL: [GET ${response.status}] ${url}`)
  }

  const contentLength = response.headers.get('content-length')

  if (contentLength && Number(contentLength) > MAX_IMAGE_SIZE) {
    throw new Error(`Image size exceeds the maximum allowed size: ${url} (${contentLength} bytes)`)
  }

  const contentType = response.headers.get('content-type')?.split(';')[0] ?? null

  if (
    !contentType ||
    !contentType?.startsWith('image/') ||
    IGNORED_CONTENT_TYPES.has(contentType)
  ) {
    throw new Error(`Invalid image content type: ${contentType}`)
  }

  const imageBytes = new Uint8Array(await response.arrayBuffer())

  if (imageBytes.length > MAX_IMAGE_SIZE) {
    throw new Error(
      `Image size exceeds the maximum allowed size: ${url} (${imageBytes.length} bytes)`,
    )
  }

  return {
    bytes: imageBytes,
    contentType: contentType,
  }
}
